name: Build 32-bit and 64-bit DLLs (Manual Trigger)

on:
  workflow_dispatch:

jobs:
  build-x64-dll:
    runs-on: windows-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Compile 64-bit DLL using MSVC
      shell: cmd
      run: |
        echo "Setting up MSVC for x64..."
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        echo "Compiling x64 DLL..."
        rem **关键改动**: 添加了 Avrt.lib
        cl.exe /D_USRDLL /D_WINDLL /utf-8 TimerResolution.cpp /link /DLL /OUT:TimerResolution_x64.dll User32.lib Avrt.lib /MACHINE:X64
        echo "x64 compilation finished."
    - name: Upload 64-bit DLL as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL-x64
        path: TimerResolution_x64.dll

  build-x86-dll:
    runs-on: windows-latest
    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4
    - name: Compile 32-bit DLL using MSVC
      shell: cmd
      run: |
        echo "Setting up MSVC for x86..."
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars32.bat"
        echo "Compiling x86 DLL..."
        rem **关键改动**: 添加了 Avrt.lib
        cl.exe /D_USRDLL /D_WINDLL /utf-8 TimerResolution.cpp /link /DLL /OUT:TimerResolution_x86.dll User32.lib Avrt.lib /MACHINE:X86
        echo "x86 compilation finished."
    - name: Upload 32-bit DLL as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL-x86
        path: TimerResolution_x86.dll
