name: Build 64-bit DLL

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-x64-dll:
    runs-on: windows-latest

    steps:
    - name: Checkout repository code
      uses: actions/checkout@v4

    - name: Compile 64-bit DLL using MSVC
      shell: cmd
      run: |
        echo "Starting 64-bit DLL compilation..."
        call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
        cl.exe /D_USRDLL /D_WINDLL /utf-8 TimerResolutionModifier.cpp /link /DLL /OUT:TimerResolutionModifier_x64.dll User32.lib /MACHINE:X64
        echo "Compilation finished."

    - name: Upload compiled DLL as an artifact
      uses: actions/upload-artifact@v4
      with:
        name: Compiled-DLL-x64
        path: TimerResolutionModifier_x64.dll
